#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x panel > /dev/null || panel &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           10
bspc config single_monocle       true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# for scratchpad
bspc rule -a notes sticky=on state=floating hidden=on
bspc rule -a assistant sticky=on state=floating hidden=on

# for scraping
bspc rule -a scrape desktop=^7 follow=on

# specific window rule
bspc rule -a firefoxdeveloperedition desktop=^1 follow=on
bspc rule -a Eclipse desktop=^8 follow=on
