require('plugins_config.lualine')
require('plugins_config.treesitter')
require('plugins_config.telescope')
require('plugins_config.completions')
require('plugins_config.fidget')
require('plugins_config.neotest')
require('plugins_config.gen')
